version: '3.4'

services:
  api1:
    image: webapiexample
    build:
      context: ./MikeyFriedChicken.DockerWebAPI.Example
      dockerfile: ./Docker/Dockerfile
    expose:
      - "11000"
  api2:
    image: webapiexample
    expose:
      - "11000"
  api3:
    image: webapiexample
    expose:
      - "11000"
  api4:
    image: webapiexample
    expose:
      - "11000"
  api5:
    image: webapiexample
    expose:
      - "11000"
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "12000:80"
    links:
    - api1:api1
    - api2:api2
    - api3:api3
    - api4:api4
    - api5:api5
  gui:
    build:
      context: ./GUI
      dockerfile: ./Dockerfile
    ports:
      - "13000:80"
